"""Create initial tables

Revision ID: 2ac1990c3d49
Revises: 
Create Date: 2025-08-10 16:48:29.659922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac1990c3d49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('product_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('original_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('stock_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('product_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('main_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sub_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sub_category_image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('product_id', name=op.f('products_pkey')),
    sa.UniqueConstraint('product_url', name=op.f('products_product_url_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
